spring:
  mvc:
    view:
      prefix: /templates/
      suffix: .html
    async:
      request-timeout: 200000s
  # 上传文件
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 1024MB
  profiles:
    active: dev
server:
  port: 8009
