spring:
  application:
    name: shuadan
  profiles:
    active: pro
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  mvc:
    view:
      prefix: /templates/
      suffix: .html
    async:
      request-timeout: 200000s
  # 上传文件
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 1024MB
server:
  port: 8009
  servlet:
    context-path: /api/